# Generated by Django 4.0.4 on 2022-05-23 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 14, 57, 12, 920823), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 14, 57, 12, 920823)),
        ),
    ]
